#!/bin/bash

if [ -z "$1" ] ; then
  echo "Usage: new pxx"
  echo $1
elif [ -e $1.hs ] ; then
    echo -n "$1 already exists - do you want to relink (y/n)? "
    read yorn
    if [ "$yorn" == "y" ] ; then
	rm jpd.hs;ln -s $1.hs jpd.hs
	ls -l jpd.hs
    fi
else
  cp p00.hs $1.hs
  rm jpd.hs;ln -s $1.hs jpd.hs
  git add $1.hs
  ls -l jpd.hs
fi
